### PR TITLE
fix:decouple gin.Context and replace with context.Context

### LINKED ISSUE #19: 修改Context
Image

Image

service层和dao层因为远古原因上下文用的都是*gin.Context, 要改成context.Context, 然后dao层的db在执行操作的时候都加上WithContext把ctx传进去, 避免请求取消但是还在操作数据库的情况

### PR DESCRIPTION
**Pull request by becky200605**
fix: https://github.com/muxi-mini-project/2025-EventGlide-Backend/issues/19

### CODE REVIEW

File: internal/middleware/jwt.go
Comment (raiki02) [inline internal/middleware/jwt.go]:
```suggestion
		rawCtx := c.Request.Context()
		rawCtx = context.WithValue(rawCtx, "studentid", c.parseSid(token))
		c.Request = c.Request.WithContext(rawCtx)
```
鉴于https://github.com/muxi-mini-project/2025-EventGlide-Backend/pull/56/changes#diff-212e08aa853fdb34613cea937a9ab93aae2455bafab63c48892a377cc4560d91R43 改了是从context.Context获取studentId, 而gin.Context和context.Context存value是隔离开来的.

**Review by raiki02 — CHANGES_REQUESTED** [review]

File: internal/dao/activity.go [hunk 1]
```diff
@@ -130,23 +130,23 @@ func (ad *ActDao) DeleteAct(c *gin.Context, a model.Activity) error {
 	}
 }
 
-func (ad *ActDao) FindActBySearches(c *gin.Context, a *req.ActSearchReq) ([]model.Activity, error) {
+func (ad *ActDao) FindActBySearches(c context.Context, a *req.ActSearchReq) ([]model.Activity, error) {
 	var as []model.Activity
 	q := ad.db // 确保 q 初始化
```
Comment (raiki02) [inline internal/dao/activity.go]: 只需要q := ad.db.WithContext(c)
下面就不需要了

**Review by raiki02 — CHANGES_REQUESTED** [review]

**Comment by raiki02** [comment]
👍
